### ISSUE TITLE
Use clap for bin options rather than a slew of environment variables

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#101]
This will make the IndraDB CLI more accessible: https://docs.rs/clap/2.33.0/clap/

**Comment by binoychitale** [comment]
Hi @ysimonson , I would like to pick up this issue. 
From what I understand the following things need to be done:
- Replace env var usage with CLI params, something like :
```bash
indradb --port=<port> --database=<conn-string>
```
By using the clap crate
Correct me if I am wrong here. If this is what we want, can I proceed with implementation?

**Comment by ysimonson** [comment]
Thanks @binoychitale! Yes, that's right. Here's the entry-point: https://github.com/indradb/indradb/blob/master/bin/src/server/main.rs

**Comment by binoychitale** [comment]
Thanks @ysimonson
I've raised a PR #107 with the changes
