### ISSUE TITLE
Binary version download

### ISSUE THREAD

**Issue by raymond-infinitecode** [indradb/indradb#122]
Currently, the software is provided as the source copy, it is a hustle for people who do not
have the proper setup to compile the rust project. e.g. Windows etc

Would the project be automated to provide binary downloads so more people will be able to
use the product directly instead of stuck in the compilation.

**Comment by ysimonson** [comment]
Yup that makes sense! And in fact this was available in some of the pre-1.0 releases, but it seems to have bitrotted at some point. It might be harder to offer windows builds, but mac and linux are definitely doable.

**Comment by ysimonson** [comment]
Done in #131, with mac and linux binaries included in releases. I can't really test it until 2.0 is out, but will address whatever issues come up then.
