### ISSUE TITLE
Add CLI client

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#141]
Right now, users can explore indradb through:

1) The [python client](https://github.com/indradb/python-client)
2) The [cap'n proto rust client](https://github.com/indradb/indradb/tree/master/proto), which is pretty rough since it's all autogenerated code
3) Via the [rust library](https://github.com/indradb/indradb/tree/master/lib).

It'd be really helpful for quick-one offs to have a CLI client as well, even if it's just for a subset of functionality.

**Comment by binoychitale** [comment]
Hi @ysimonson , I would like to pick this up. 
Here's what I think can be done -
1. Create a CLI either from scratch or using an external lib (like [shrust](https://github.com/phsym/shrust))
2. Internally use the Rust library to interact with the indraDB instance(like in the [wikipedia example](https://github.com/indradb/wikipedia-example/blob/master/inserter/src/main.rs))

Do you think this is the right way to go about things?
What operations should be exposed initially via the CLI?

**Comment by ysimonson** [comment]
Thanks @binoychitale! I think that makes sense:

1. The binary could be a separate binary under a new directory (`client`) in this repository. I don't think it should be interactive though, that makes it more difficult to automate in scripting. Instead, each action could be a separate clap sub-command.
2. Yeah internally using the Rust library makes sense.

This isn't quite ready to address yet, since I'm [likely going to swap out the API frontend.](https://github.com/indradb/indradb/pull/142) Luckily, once that's done, this'll actually be a lot easier to tackle, since the tonic-generated includes some nice ergonomic improvements. Once that's done, I'm happy to wire up the scaffolding - since it's going to be a lot of work, it can be done in a piecemeal fashion.

**Comment by ysimonson** [comment]
gRPC interface swapped in. I'm adding in the scaffolding for the client now, after which this'll be unblocked.

**Comment by ysimonson** [comment]
[Scaffolding is done.](https://github.com/indradb/indradb/blob/master/client/src/main.rs)

**Comment by binoychitale** [comment]
Maintaining progress in a draft PR - #157 so that we can track progress and course correct in case of any issues
