### ISSUE TITLE
Use value_t! macro on CLI arg parsing

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#143]
We could use [clap's value_t! macro](https://docs.rs/clap/2.33.0/clap/macro.value_t.html) to simplify parsing the integer arguments in `cli.rs`.

**Comment by binoychitale** [comment]
Hey @ysimonson , I was thinking of picking this up.
I wanted to understand what specifically would be the advantages of replacing the current `matches.value_of(...).parse::<...>().expect(...)` syntax with the `value_t!` macro

According to the [source](https://docs.rs/clap/2.33.0/src/clap/macros.rs.html#61-77), we would still need to handle errors from empty arguments and invalid parsing separately.
From what I can understand, this would leave the parsing logic more or less the same from a "lines of code" perspective

**Comment by ysimonson** [comment]
You wouldn't need to handle parse errors separately. `value_t!` will either return a value with the type you're trying to parse into, or a standard error. So, e.g. this:

```rust
matches.value_of(ROCKSDB_MAX_OPEN_FILES).unwrap().parse::<i32>().expect(
    "Could not parse argument `max_open_files`: must be an \
     i32",
)
```

could be replaced with this:

```rust
value_t!(matches, ROCKSDB_MAX_OPEN_FILES, i32).unwrap_or_else(|e| e.exit())
```

**Comment by binoychitale** [comment]
Ah my bad. I forgot about the defaults values we have set in clap.
I'll spin up a PR for this :)
