### ISSUE TITLE
server: add feature flags for backends

### ISSUE THREAD

**Issue by zseri** [indradb/indradb#165]
Currently, the server is just build with all available backends included. In production and similiar environments it would be a good idea to just compile it against the one or two backends (if in-memory is always enabled) that are going to be used and omit others, to reduce the binary size of the indradb-server binary. It is possible to just include all these feature flags into the `default` feature set, to retain the current default behavoir.

**Comment by ysimonson** [comment]
What would be the specific concern about using the current binary in production?

**Comment by zserik** [comment]
binary size and not good enough customizability (minimal principle)
```
cargo build --release
original sizes:
12M     target/release/indradb-client
16M     target/release/indradb-server

LTO + cargo rustc --release -- -C target-cpu=native
sizes:
5,8M    target/release/indradb-client
12M     target/release/indradb-server

no significant size change for client if deps on sled+rocksdb is removed but the server size if reduced.
5,8M    target/release/indradb-client (no dep on sled, no dep on rocksdb)
11M     target/release/indradb-server (rocksdb + memory)
7,4M    target/release/indradb-server (sled + memory)

if sled+rocksdb support is removed from the server, size goes down even more:
5,6M    target/release/indradb-server (memory)
```

**Comment by zserik** [comment]
Conclusion: If one only needs the in-memory backend, the server executable is considerable bloated.

**Comment by ysimonson** [comment]
I wouldn't consider 16mb "bloated", and support for this would require the use of `cfg_if`, which would add its own size and complexity to the code base.

Support for this might make sense if the in-memory backend ever becomes something resembling "production ready", but it needs [persistence](https://github.com/indradb/indradb/issues/164) and some fuzzer runs (it's been too longer since the fuzzer was last run.)

**Comment by zserik** [comment]
As this only affects very few code locations, it could be implemented solely using `#[cfg(feature = "...")]`, and thus wouldn't require `cfg-if`, and additionally, `cfg-if v1.0.0` is currently already included in the compilation via dozens of crates on which `indradb-lib` and `indradb-proto` depend.

**Comment by ysimonson** [comment]
Especially now that sled has been removed from core, I think the savings here would be too marginal to be worthwhile — especially since the intersection of people who want to use the server, don’t want rocksdb, and need to minimize the size of the binary is likely very small.
