### ISSUE TITLE
Add a `--repair` flag

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#171]
The `rocksdb` subcommand in the CLI should take a `--repair` flag. Rather than starting a server, this will run [repair](https://github.com/indradb/indradb/blob/1bac7a47c3e8ad45de6d922dee4f01690f1f7889/lib/src/rdb/datastore.rs#L249-L259) on the datastore at the given path.

**Comment by WatsonThink** [comment]
If you don't mind, can you assign this to me?

**Comment by ysimonson** [comment]
Sure thing!
