### ISSUE TITLE
docs unclear on usage, querying

### ISSUE THREAD

**Issue by bionicles** [indradb/indradb#179]
would you be openminded to work on the docs? this project sounds interesting but the docs are nonexistent so i can't even start to evaluate it

**Comment by ysimonson** [comment]
If you're looking for API docs:

* When using IndraDB as a rust library, the docs are [here](https://docs.rs/indradb-lib/2.1.0/indradb/)
* When running IndraDB as a server and interfacing through rust, the docs are [here](https://docs.rs/indradb-proto/2.1.0/indradb_proto/)
* When running IndraDB as a server and [interfacing through python](https://github.com/indradb/python-client), the docs are [here](https://indradb.github.io/python-client/indradb/)

If you're looking for a concrete example, there's one of using IndraDB as a server and interfacing through rust [here](https://github.com/indradb/wikipedia-example). I think more examples would be helpful and would definitely welcome contributions. Most pressingly we need an example of interfacing with IndraDB through python. Demonstrations of using the new client CLI, or the embedded library, would be helpful too.

**Comment by bionicles** [comment]
Dude, the Rust Graph DB idea, is amazing.  I'm sure this was a ton of work and not easy.  Would you be open minded to please show in some simple code block(s) in the readme, how it should be used?  Literally just making a graph, adding stuff, querying it, create read update delete search etc etc -- i'd use it as a rust lib, but pythonistas are quite common as well, and a CLI sounds pretty awesome. 

Nobody's more qualified to write usage examples than creators, and usage examples are the most critical form of documentation.  Simple usage examples could be a single code block in backticks at the top of the readme, and could take under 10 minutes to write, and dramatically ease onboarding of new users.  Pretend you're a new user. You look at the readme, click the link to the website. There's two links on the website. Where do they go?

Thanks so so much for making this.  Thanks for the links.  I am keen to use it and contribute, and will look at them!

**Comment by ysimonson** [comment]
The problem is that using rust as a library is more of an advanced user feature, so putting it on the readme would incorrectly imply that it's the primary way of interacting with IndraDB. gRPC is the default course, which is demonstrated through rust e.g. [here](https://github.com/indradb/wikipedia-example/blob/master/src/indexer.rs), and python [in its tests.](https://github.com/indradb/python-client/blob/master/indradb/test/test_client.py)

**Comment by bionicles** [comment]
If these are the preferred ways to use it, why not include them in the Readme? Otherwise new users need to dig into your tests just to figure out how to use it...in my experience, when things aren't documented, they aren't used - people will just switch to something else which has great docs

Seems odd to spend huge amounts of hard work to develop a cool project then skip writing a few code blocks in the Readme to show folks how to use it

**Comment by ysimonson** [comment]
Sure, this is good feedback, and I'll keep it in mind. In the mean-time, you've got links now to API docs, examples, and tests. That should be enough to get started.
