### ISSUE TITLE
RocksDB: Investigate multi-threaded column family operations

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#186]
The RocksDB lib now supports [mutli-threaded column family operations](https://docs.rs/rocksdb/0.17.0/rocksdb/type.DB.html). Run benchmarks of this vs the currently configured "single-threaded" variant.

**Comment by C0MM4ND** [comment]
Hello indradb team, I'm now inserting more than giga V & E with `indradb::RocksdbDatastore` and I found it takes 100% of only one cpu core, others are all idle. I want all cores working hard, because single core is weak in server-side CPU. However I cannot find any *multi-thread* related issue or document except this enhancement. 
So am I in right place? If so I'm willing to help do some benchmarks and take pull requests.

**Comment by ysimonson** [comment]
Yes that's right. Offhand that's the only single-threaded bottleneck I can think of in the rocksdb implementation.

**Comment by ysimonson** [comment]
Looking at rocksdb's docs, I hadn't noticed [this section](https://docs.rs/rocksdb/latest/rocksdb/type.DB.html#limited-performance-implication-for-single-threaded-mode) before. Given that this would only enable multi-threaded operations for cf modifications, which only happens when the database is first initialized, this isn't going to improve performance.

I'm not sure then why you were seeing single-threaded inserts, but my first guess is that it has something to do with the [options we're seeing.](https://github.com/indradb/indradb/blob/8f5bad2d62b0ddf9b90c9e38ebb211f20b8a3025/lib/src/rdb/datastore.rs#L25)

In terms of the microbenchmark results you have, I suspect the difference you're seeing is in [using `Arc` instead of refs](https://github.com/indradb/indradb/compare/master...C0MM4ND:indradb:master).

**Comment by C0MM4ND** [comment]
My cpu use problem has been solved by `opts.increase_parallelism(num_cpus::get().try_into().unwrap())`, doc [here](https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#examples-1). 
I don't know whether it is a good option to most scene. So I think it would be better to provide a `new_db_with_options` as #276.

**Comment by ysimonson** [comment]
Nice catch! Adding parallelism as an option for compaction makes sense. I don't think multi-threaded CFs does, though, for the aforementioned reasons. I'll close out this ticket since this is about multi-threaded CFs, but review the PR separately.
