### ISSUE TITLE
Move off of the iron web framework

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#19]
Move off of the iron web framework, which is not currently maintained. The most obvious candidate is rocket, but the framework currently only works on rust nightly. See progress on their support for rust stable here: https://github.com/SergioBenitez/Rocket/issues/19

**Comment by dataf3l** [comment]
@ysimonson Theorethically one could also move to Hyper, although with the recent changes from 0.9 -> 0.11 and the inclusion and Tokio and Futures, it can be an undertaking, until the Hyper team provides easy examples for us mere mortals...

**Comment by ysimonson** [comment]
Yes, or actix-web which is currently getting a lot of attention for its benchmark numbers. Right now, though, I'm experimenting with grpc (#15). This would do away all-together with the need to directly use a web framework, and make composition of client libraries easier, at the expense of using protobufs which throws away a lot of the nice things about serde + rust's type system.

**Comment by ysimonson** [comment]
Addressed in #37
