### ISSUE TITLE
ValidationError encountered in Datastore impl can't be extracted w/ `?` without conversion

### ISSUE THREAD

**Issue by jasongoodwin** [indradb/indradb#206]
May be helpful to include a trait in errors to flip these. 
I can see some major structural/api breaking changes so I won't push a PR for this yet. Let me know your plan and I can help tho.

Example error:
```
   --> src/datastore.rs:535:65
    |
535 |                         let ident = Identifier::from_str(&*name)?;
    |                                                                 ^ the trait `From<ValidationError>` is not implemented for `indradb::Error`
    |
```

I just have a little helper
```

fn from_validation_error(e: ValidationError) -> Error {
    indradb::Error::Datastore { inner: Box::from(e) }
}
```

But only because I can't myself implement From for Error

```
impl From<ValidationError> for Error{
    fn from(e: ValidationError) -> Self {
        indradb::Error::Datastore { inner: Box::from(e) }
    }
}
```

Probably some scope/categorization concern - I don't think that's an `Error:Datastore`!

**Comment by ysimonson** [comment]
Breaking changes aren’t a concern right now since the stuff on master is going to be 3.0. But what’s the motivation for this conversion? They’re distinctly separate error classes, and at least in the lib code, there isn’t a need for this.

**Comment by jasongoodwin** [comment]
Thanks for engaging. I had a good look to understand why this is an issue in our backend, but not in yours.
Currently the rdb implementation reads identifiers from the database via this utility method:

```
/// Reads an identifier from bytes.
///
/// # Arguments
/// * `cursor`: The bytes to read from.
pub fn read_identifier<T: AsRef<[u8]>>(cursor: &mut Cursor<T>) -> models::Identifier {
    let t_len = {
        let mut buf: [u8; 1] = [0; 1];
        cursor.read_exact(&mut buf).unwrap();
        buf[0] as usize
    };

    let mut buf = vec![0u8; t_len];
    cursor.read_exact(&mut buf).unwrap();

    unsafe {
        let s = str::from_utf8_unchecked(&buf).to_string();
        models::Identifier::new_unchecked(s)
    }
}
```

Which is in an unsafe block. Our implementation is pushing string into identifiers via `Identifier::new` which generates a Validation error. I suppose what we should be doing is assuming that the validation is done on the way in and then using an unchecked identifier. I was avoiding unsafe, but I can see how you are doing it with rocks.

**Comment by jasongoodwin** [comment]
Orthogonal, should the unchecked methods really be marked `unsafe`? 
Sorry for the dumb q - I've only been working with rust for 6 months or so. 
I'm just wondering if the fact that it panics if validation fails really warrants the unsafe marker. I haven't worked with any unsafe code in rust so bear with me here, but what I understand is that unsafe means unsafe with regard to memory access - eg dereferencing a raw pointer shared across threads and mutating the state that's shared without any locking mechanism..

**Comment by jasongoodwin** [comment]
(re-opened hoping for advice, will close again once we understand the correct approaches in implementing backends that read Identifiers)

**Comment by ysimonson** [comment]
It’s unsafe because what’ll happen if the identifier isn’t valid is undefined. It likely won’t panic, but instead propagate the invalid identifier to consumers.

Lib makes this shortcut because it’s faster, and will only reach this undefined behavior if the database is corrupted.

**Comment by jasongoodwin** [comment]
sounds good - thanks!
