### ISSUE TITLE
Test Suite requires ordering in result to match input but that puts a need for result order on implementations

### ISSUE THREAD

**Issue by jasongoodwin** [indradb/indradb#233]
See: https://github.com/indradb/indradb/blob/master/lib/src/tests/bulk_insert.rs#L51

Why are these checks not for contains rather than being in a specific index? I'm implementing a sharded solution right now and this test fails periodically because of this conditional requirement.
I haven't thought about it a lot, but I can't see why the api should require determinism like that, that input matches output, as the response has the requisite data (eg the vertex w/ the id that was made on the request.)

Lmk your thoughts here - I'll either push a pr, or else change my impl.

**Comment by ysimonson** [comment]
There’s no need for the ordering. And there’s probably a crate out there that would make the matching more pleasant.

**Comment by jasongoodwin** [comment]
I talked to a peer about this and it may make sense to order the output based on input. 
I've looked at other database implementations and, for example, mysql will return the results based on their order on disk rather than with any specific order unless an `order by` clause is given.

`select * from users where id in (1,2,3);`' will give no specific order unless you `order by id;`

Cypher query language has an `order by`

```
MATCH (n)
RETURN n.name, n.age
ORDER BY n.age, n.name
```

My peer thinks we should continue to order the results in our `Datastore` impl.

**Comment by jasongoodwin** [comment]
Yeah I've thought about it and I'm with you @ysimonson but without a clear path for order by semantics in scope, it's probably reasonable to assume that the order of the results is correlated with output. 
For now, I've modified our implementation to match the expectations of the test suite, that the results across sharded data should be ordered on the requested input. It's like comparing apples and oranges, but it deviates from eg postgres/mysql default sort of insertion order.

`select * from table where id in (1,2,3)` would return the ids in the order they are created rather than with any sort order. There is no explicit or implicit expectations so this is ambiguous to me at this point.

I think I might close this ticket for now, but I will likely make prs against the test suite as I keep building on a sharded solution on indra to ensure the coverage is sufficient.
