### ISSUE TITLE
PropertyValueVertexQuery returns Err(NotIndexed) while PipePropertyValueVertexQuery does not.

### ISSUE THREAD

**Issue by cedtwo** [indradb/indradb#236]
The following line will return a `Ok([])`
```
let q = RangeVertexQuery::new()
        .t(my_type)
        .limit(5)
        .with_property_equal_to(
            Identifier::new("Name").unwrap(),
            "John".into());

let result = db.get_all_vertex_properties(q.into());
```
Which is incorrect as this vertex exists. The following line, however, returns an `Err(NotIndexed)`, which clarified why the above line did not return anything:
```
let q = PropertyValueVertexQuery::new(
        Identifier::new("Name").unwrap(),
        "John".into());

let result = db.get_all_vertex_properties(q.into());
```
Should the first query return an error too, clarifying that this predicate is inappropriate on a non-indexed field?

**Comment by ysimonson** [comment]
Yeah this is a bug, nice catch!

**Comment by ysimonson** [comment]
Looks like this issue is resolved, maybe by the v4 changes. Test in #289.
