### ISSUE TITLE
Documentation / Tutorials

### ISSUE THREAD

**Issue by cowboyd** [indradb/indradb#238]
Indradb looks very interesting, but I don't find a link to any query syntax or anything. How does one even get started?

**Comment by OZoneGuy** [comment]
Just starting with you as well. If you want a client to query some server, you should look at `indradb-proto`. Provides a proto file with the definitions: https://github.com/indradb/indradb/blob/06134dde5bb53eb1d2aaa52afdaf9ff3bf1aa674/proto/indradb.proto. I search the file for functions that could fit my need and read the comments. The comments are clear and the functions and the types are well named.

How to use the server? I am planning to just put it in docker and calling it a day :/ Can't help with that part...

I agree that it is missing documentation. Maybe I can try documenting and providing better examples when I get more familiar with it.

That being said, I am having trouble actually using it. I added it to my toml file, using rust lang, and I can't import anything under `indradb_proto::indradb`. Probably irrelevant to you if you are not using rust. But something to note if you are.

**Comment by cowboyd** [comment]
Thanks @OZoneGuy! Very helpful.

**Comment by ysimonson** [comment]
The API are docs are solid, but it could use some more examples/tutorials.

* If you want to use it as a rust library, see the [indradb-lib crate docs](https://docs.rs/indradb-lib/3.0.1/indradb/).
* If you want to interface with the server with a rust client, see the [indradb-proto crate docs](https://docs.rs/indradb-proto/latest/indradb_proto/), and the [wikipedia example](https://github.com/indradb/wikipedia-example). @OZoneGuy the wikipedia example should also give an idea of how to use the server.
* If you want to interface with the server with a python client, see the [python library docs](https://indradb.github.io/python-client/indradb/) and the [python repo more broadly](https://github.com/indradb/python-client). There aren't good examples, but the tests should give an idea of how to use it.

**Comment by ysimonson** [comment]
Added a bunch of examples in #245. Hope that helps.
