### ISSUE TITLE
Recursive query

### ISSUE THREAD

**Issue by stellanhaglund** [indradb/indradb#250]
Hello!
Is there a way to do recursive queries?

I would need to get like a tree structure with all the children of a vertex to the depth where there are no more relations , and if I use it rocks or in memory I don’t really see a problem in having to build the recursive part in code but if I use postgres or if I use the library server then there will be network traffic back and forth for every step and I would like that not to be the case.

Thanks,

**Comment by ysimonson** [comment]
Getting the output over multiple hops isn't supported natively, but you could achieve it without multiple network round-trips with plugins. As the plugin crawls over the graph, it can stream results back to the client. See also #180.

**Comment by ysimonson** [comment]
This will be supported in the forthcoming v4, via include()
