### ISSUE TITLE
clarify "properties"

### ISSUE THREAD

**Issue by milahu** [indradb/indradb#251]
> IndraDB departs from TAO (and most graph databases) in its support for properties.

what are properties?

should be in the readme

**Comment by milahu** [comment]
sorry, still unclear

> IndraDB departs from TAO (and most graph databases) in its support for properties, **a queryable mapping of string keys to JSON values tied to nodes and edges**.

how about something like

> IndraDB departs from TAO (and most graph databases) in its support for properties.
>
> **Properties are attached to all nodes and edges. Properties can hold arbitrary user-defined data. `indradb` will store this data in JSON encoding.**

is that correct?

also, why do other engines not support this?

maybe add a small example?

if this is such a rare feature, it should be described more

**Comment by cedtwo** [comment]
I was not confused about what properties are until I read this issue. Does having properties really make IndraDB different to "most graph databases"? From my understanding it's extremely common to add metadata to vertices and edges, such as edge weighting etc.

**Comment by ysimonson** [comment]
@milahu TBH I don't think that's any more clear.

@cedtwo yeah that's fair, fixed: https://github.com/indradb/indradb/commit/40db313505db57bd5c45cc1361c7ed10e3c00a15
