### ISSUE TITLE
Helper function to write rust struct to vertexproperty

### ISSUE THREAD

**Issue by askasp** [indradb/indradb#273]
Is there a way to inject a serialized struct directly into a vertexproperty?

For now i'm thinking of doing something like this, but it seems very tedious. 

pub fn create_bulk_insert_form_serde(vertex_name: String, blob: serde_json::Value) -> Vec<indradb::BulkInsertItem>{
    let mut inserts = Vec::new();
    let user = Vertex::new(Identifier::new(vertex_name).unwrap());
    inserts.push(indradb::BulkInsertItem::Vertex(user));
    for (key, value) in blob.as_object().unwrap() {
    inserts.push(indradb::BulkInsertItem::VertexProperty(
                user.id,
                indradb::Identifier::new(key).unwrap(),
                serde_json::Value::String(value.to_string()),
            ))    
}  
Another alternative is to have the whole data wrappe in a "data" key and use serde_json::Value::object.. but I assume that will be harder to query

**Comment by ysimonson** [comment]
You're treating `blob` as a map, which is making it more complicated than it needs to be:

```rust
pub fn create_bulk_insert_from_serde(vertex_name: String, blob: HashMap<String, serde_json::Value>) -> Vec<indradb::BulkInsertItem> {
    let mut inserts = Vec::new();
    let user = Vertex::new(Identifier::new(vertex_name).unwrap());
    inserts.push(indradb::BulkInsertItem::Vertex(user));
    for (key, value) in &blob {
        inserts.push(indradb::BulkInsertItem::VertexProperty(
            user.id,
            indradb::Identifier::new(key).unwrap(),
            blob,
        ));
    }
    inserts
}
```

Not sure what you mean about wrapping the key, it's always an identifier.
