### ISSUE TITLE
Question about query details

### ISSUE THREAD

**Issue by MTRNord** [indradb/indradb#293]
Hi,

I am trying to use this as an underlying storage for a graph based search "thing" (for lack of a better description).

I am wondering are queries for values exact match queries, or is it checking if the value contains the query value?

**Comment by MTRNord** [comment]
To give some more detail on what I am trying to solve:

![image](https://user-images.githubusercontent.com/1374914/232167034-c76be857-f8bb-429a-bd8e-beb6c5bead8f.png)

I have the matrix events as a known graph part and I have a flexible indexer framework which can interact and might have a second indexer for websites. Finding the edges within one indexer is easy since I know the data while inserting. But when I am trying to insert the data I also want to generate edges to websites.

The idea here was to do a fulltext based search on the graph to find nodes where the words (excluding stopwords) match certain properties. For example having a message "I found recently indradb" should generate an edge to a website "docs.rs/indradb" assuming I have it indexed. The actual edge generating is "easy" if I have a fulltext search but from how I understand it indradb does not have this correct?

And if i have a list of things as a property value I cannot query for "contains X in list" for example? I would need to generate vertexes on the graph per word, add edges to the documents and then query via that to have a fulltext search with indradb correct?

**Comment by ysimonson** [comment]
> I am wondering are queries for values exact match queries, or is it checking if the value contains the query value?

I’m not sure if I’m following, but there are queries both for the presence of a property, and queries for a specific property value.

**Comment by ysimonson** [comment]
> And if i have a list of things as a property value I cannot query for "contains X in list" for example? I would need to generate vertexes on the graph per word, add edges to the documents and then query via that to have a fulltext search with indradb correct?

Yes that’s right, although a dedicated full text search engine is likely a better choice.
