### ISSUE TITLE
Unable to Instantiate new Database Struct from Library

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [indradb/indradb#296]
Hey Team,

Loving IndraDB so far after learning it the last few weeks.

I reviewed the changes made to 4.0.0 and have been trying to refactor my code to use the new Database struct, however, I am having trouble instantiating a new database for even the most trivial example.

`
#[cfg(test)]
mod tests {
    use indradb::{Database, MemoryDatastore};

    #[test]
    fn create_database() {
        let datastore = MemoryDatastore::new_db();
        let database = Database::new(datastore);

        assert!(database. Sync());
    }
}
`
I have tried making this work, and it seems fairly straightforward, it should be fine since the MemoryDatastore implements the correct Datastore trait.

However, running cargo test result in the compiler throwing a "trait bounds is not satisfied" error stating "the trait 'indradb::Datastore' is not implemented for Database<MemoryDatastore>. Sorry if I am just missing something super simple, I have been trying to get this small example to compile for hours and I simply don't understand what could be going wrong?

**Comment by ysimonson** [comment]
`MemoryDatastore::new_db` returns a `Database`, so you don't call `Database::new`. Also, the assert there

```rust
#[test]
fn create_database() {
    let db = MemoryDatastore::new_db();
    db.sync().unwrap();
}
```

**Comment by ca-mantis-shrimp** [comment]
Thank you! Feel free to close.

Loving the database and appreciative for all the amazing work your team is doing 😁
