### ISSUE TITLE
Support for undirected edges?

### ISSUE THREAD

**Issue by dmyyy** [indradb/indradb#299]
Is there an easy way to represent undirected edges using the current API? Is the correct way to just add a reversed edge every time you add an edge?

**Comment by ysimonson** [comment]
>  Is the correct way to just add a reversed edge every time you add an edge?

yes that’s right. Although bear in mind that querying for edges in reversed order is just as efficient as in “forwards” order. ie if there is an edge A->B, you can equally efficiently query for edges inbounding to B. For some use cases that may be adequate.

**Comment by dmyyy** [comment]
@ysimonson Super useful - thank you! I was also wondering - is there deterministic traversal of the graph db?

I saw a post here a couple years ago - is https://github.com/indradb/indradb/issues/59 still the best way to do traversal in indradb or has something changed since 2019?

**Comment by ysimonson** [comment]
If you're traversing the entire graph, it's generally going to be `O(nodes)`, and there isn't a way for anything to be more efficient. If you're looking up an individual node, that's going to vary by the underlying implementation. The in-memory implementation does use btrees, so it'd be `O(log n)`.

It's a lot easier to walk the entire graph than #59 nowadays. You can just issue an [`AllVertexQuery`](https://docs.rs/indradb-lib/latest/indradb/struct.AllVertexQuery.html).

**Comment by dmyyy** [comment]
@ysimonson Sorry for the continued questions - I was wondering if it's possible to modify a vertex/edge identifier? From looking at the database api I don't see a way (query returns a copy of the value). Seems like deleting the vertex/edge and adding a new one with the same uuid and modified identifier is the only way. 

It would be useful to have something along the lines of `update_vertex(), update_edge()` in the database api

**Comment by ysimonson** [comment]
That's right. You could alternatively give the vertex or edge a property, which has the flexibility of being update-able. If you need to query by property value, you'd just index that property.

If it must be the type, could you explain the usecase? I'm having trouble thinking of examples where someone would want to change it.

**Comment by dmyyy** [comment]
I'm working on a graph rewriting application - intuitively it makes sense for me that labels on vertices can be changed. Working around this with properties works totally fine for my use case.
