### ISSUE TITLE
What is the use case for Vertex Type?

### ISSUE THREAD

**Issue by slyons** [indradb/indradb#301]
Just poking around this library for the first time and I've got a question: What's the use for the Identifier when creating a Vertex? It's not tied to the ID, and it doesn't seem to be queryable. 

If anyone could shed some light on this I'd appreciate it.

**Comment by dmyyy** [comment]
You can query vertices by ident using the range query.

**Comment by ysimonson** [comment]
Yeah you can query for it. I’ve also found that most of the time you want to differentiate between different types of vertices, which is what types do.
