### ISSUE TITLE
Replace BTree with indexset behind a feature

### ISSUE THREAD

**Issue by dmyyy** [indradb/indradb#302]
[Indexset](https://github.com/brurucy/indexset) promises to be an improvement over a regular BTree 
- Twice as fast to iterate
- 3400x times faster to get the i-th element
- Approximately 10% faster for lookups

The downside is that insertions are two times slower

This seems like an across the board improvement over the stdlib BTree for graph db use cases - it would be nice to see this behind a feature. 

It could also help guarantee determinism since search order is fixed which may be a useful property.

Could also have a pretty significant speedup in specific_vertices, and specific_edges if the vertex/edge uuid corresponds to the index in the BTree

**Comment by dmyyy** [comment]
It could also help guarantee determinism since search order is fixed which may be a useful property.

**Comment by dmyyy** [comment]
Not quite a drop-in replacement - I left an issue: https://github.com/brurucy/indexset/issues/1

**Comment by ysimonson** [comment]
This looks interesting! Worth keeping an eye on, but I do think it’s too early to use, given the readme warning:

> This is beta quality software, so use it at your own risk.

**Comment by dmyyy** [comment]
Totally agree - but it needs to be used for bugs to be discovered/for it to be improved. 

Putting it behind a feature (maybe with a big disclaimer warning somewhere in the docs) lets interested people (like me) easily play around with it (without having to fork indradb)

**Comment by ysimonson** [comment]
Makes sense, feature flag or separate data store implementation would both work.

**Comment by brurucy** [comment]
Just dropping by to say that `indexset`'s `BTreeMap` and `BTreeSet` can now be used for all use cases in `indradb` in which their std lib versions are used

**Comment by dmyyy** [comment]
Thanks for your work - I have a branch that replaces all BTree usage locally, just trying to take it a step further and seeing if specific_vertices/specific_edges/properties transactions can take advantage of the constant time lookup (by storing the mapping of vertex/edge/property to index)/ making the implementation more flexible.

I'm still not sure what I would do in the remove_vertices/remove_edges (there's a couple directions I can take)
- Disallow removing vertices/edges (works for my use case but not sure how generally useful this will be)
- Use the vertex/edge to index maps as a cache which is invalidated when a vertex/edge is inserted/removed

Just thinking out loud - I would need to
- [ ] New datastore?
- [ ] Implement Ord on Edge/Vertex types
- [ ] Write some benchmark tests to see if there is a perf boost/this change is worth adding

Cache
- [ ] Invalidate the cache for indices > rank of inserted/removed vertex/edge

**Open Questions**
- What if the client wants to mix/match behavior? In my use case vertices/edges never change but properties change often
- Is there a sensible default for the above behavior (e.g. use Indexset for vertices/edges and std::BTreeSet for properties all the time)? 
- What should the implementation look like (heavily dependent on the first question)

Trying to balance building something generally useful vs. hyper-optimizing for my use case

@ysimonson Would love to hear your thoughts/ideas on this

@brurucy Just wanted to confirm - am I correct in assuming re-sorting only happens on insertion/deletion (or am I missing something here)

**Comment by brurucy** [comment]
> Thanks for your work - I have a branch that replaces all BTree usage locally, just trying to take it a step further and seeing if specific_vertices/specific_edges/properties transactions can take advantage of the constant time lookup (by storing the mapping of vertex/edge/property to index)/ making the implementation more flexible.
> 
> I'm still not sure what I would do in the remove_vertices/remove_edges (there's a couple directions I can take)
> 
> * Disallow removing vertices/edges (works for my use case but not sure how generally useful this will be)
> * Use the vertex/edge to index maps as a cache which is invalidated when a vertex/edge is inserted/removed
> 
> Just thinking out loud - I would need to
> 
> * [ ]  New datastore?
> * [ ]  Implement Ord on Edge/Vertex types
> * [ ]  Write some benchmark tests to verify there is a perf boost/this change is worth adding
> 
> Cache
> 
> * [ ]  Invalidate the cache for indices > rank of inserted/removed vertex/edge
> 
> **Open Questions**
> 
> * What if the client wants to mix/match behavior? In my use case vertices/edges never change but properties change often (is it even possible to abstract across different types this way? We could write our own BTreeCollection trait that we can then create a CustomInternalMemory to be generic over)
> * Is there a sensible default for the above behavior (e.g. use Indexset for vertices/edges and std::BTreeSet for properties all the time)?
> * What should the implementation look like (heavily dependent on the first question)
> 
> Trying to balance building something generally useful vs. hyper-optimizing for my use case
> 
> @ysimonson Would love to hear your thoughts/ideas on this - looking for some buy-in on the possible merge-ability of this kind of change before I start on the work
> 
> @brurucy Just wanted to confirm - am I correct in assuming re-sorting only happens on insertion/deletion (or am I missing something here)

Yes.

I'd also like to point out, that there is a way to make `indexset::BTreeSet` and `indexset::BTreeMap` with more bearable insertion times.

**Comment by dmyyy** [comment]
> I'd also like to point out, that there is a way to make indexset::BTreeSet and indexset::BTreeMap with more bearable insertion times.

Sounds good to me - the idea of mixing two different BTree implementations by abstracting over it via a trait sounds too hacky anyways - having the custom internal memory implementation backed by the same btree with flexibility exposed to the client sounds way cleaner to me.

> I will make a new release, that will contain a new way to create a btree, new_with_bucket_capacity, that will provide that feature.

Looking forward to testing out the change

**Comment by brurucy** [comment]
> > I'd also like to point out, that there is a way to make indexset::BTreeSet and indexset::BTreeMap with more bearable insertion times.
> 
> 
> 
> Sounds good to me - the idea of mixing two different BTree implementations by abstracting over it via a trait sounds too hacky anyways - having the custom internal memory implementation backed by the same btree with flexibility exposed to the client sounds way cleaner to me.
> 
> 
> 
> > I will make a new release, that will contain a new way to create a btree, new_with_bucket_capacity, that will provide that feature.
> 
> 
> 
> Looking forward to testing out the change
> 
> 
> 
> Would also be interested in general guideline for bucket capacity numbers - Are these 1024/128 numbers assuming anything about node size? I noticed in your test you seem to mostly be using 4 byte integers as keys - if I wanted to use a 32 byte key for edges (two uuid's) or a 24 byte key for properties (String). Or is this something hardware-specific (based on cache-size) and thus needs to be benchmarked per-machine? 

I've just released it. The function is called "with_maximum_node_size".

I've got quite different results on different architectures, but it doesn't ever get faster (in terms of insertions) than the std lib. It does get very close though (around 20% slower) on x86, using 128 as maximum node size.

Anyhow, now you're able to have many different BTrees, with different node sizes.

**Comment by ysimonson** [comment]
This all sounds good to me, and yeah I don’t see anything preventing this from being merged so long as it’s a separate datastore that’s feature flagged / off by default.

Regarding deletion, is it possible to replace values with tombstones? Or another option would be to have a separate BTree of deleted vertices/edges, and query both. I’m not sure how bad a performance hit that would be. The final option is to just disallow removal, but that’s going to constrain what tests/benchmarks you can run. 

For benchmarking, there’s a standard benchmarking suite. It’s runnable via make bench.

**Comment by dmyyy** [comment]
Just an update - I did some caching benchmarks and the second lookup basically negated any benefit from the indexed B-Tree. 

The motivation was to have a fast in-memory datastore, and the performance characteristics of the indexed B-Tree seemed appealing at the time. After spending more time in this space I feel like a fast in-memory datastore would probably look like `petgraph`'s GraphMap and not be backed by a B-Tree unfortunately.

Thanks for the quick updates @brurucy - sorry I didn't end up using your work
