### ISSUE TITLE
Is there a reason Vertex and Edge aren't Copy?

### ISSUE THREAD

**Issue by dmyyy** [indradb/indradb#308]
Both Uuid and Ident are Copy so Vertex/Edge can be Copy as well (unless I'm missing something)

**Comment by ysimonson** [comment]
I don’t know of a recommended byte size for things to be made Copy, but figured 16 is a good heuristic. At that point, UUID fits. Idents for the most part don’t, so I’m sort of cheating there. I felt like Vertex and Edge would be pushing it too far. But I don’t have a strong opinion on this. Would it be substantially more convenient to be Copy?

**Comment by dmyyy** [comment]
That makes sense - reading up on it some more that seems to be the correct choice. I was unsure if I should be using references to avoid copying (since the internals are cheap to copy) - sounds like references it is
