### ISSUE TITLE
cargo build in Archlinux failed as failed to build librocksdb-sys v0.8.3+7.4.4

### ISSUE THREAD

**Issue by Curricane** [indradb/indradb#311]
Env:
os: ArchLinux  5.15.133.1-microsoft-standard-WSL2
rustc: rustc 1.74.1 (a28077b28 2023-12-04)
indradb: master  f9a0467dbac5e389ead06ca4e4ca47098ec80cb4

detail:
[error.txt](https://github.com/indradb/indradb/files/13774920/error.txt)

and i find the similar question in https://github.com/rust-rocksdb/rust-rocksdb/issues/813 

it said that we need update librocksdb-sys to v0.11.0+8.1.1

**Comment by Curricane** [comment]
fix rocksdb = { version = "0.19.0", optional = true } to  rocksdb = { version = "0.21.0", optional = true } in indradb/lib/Cargo.toml will solve this problem

**Comment by ysimonson** [comment]
This should be fixed with #313
