### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by djKooks** [indradb/indradb#33]
Hello
First, thanks for developing/managing great project.
I'm just trying to build this project with `cargo build`, and faced on some error.
```
warning: redundant linker flag specified for library `c++`

   Compiling rocksdb v0.8.3
   Compiling indradb-lib v0.15.0 (file:///Users/kwangin/workspace/indradb/lib)
error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
   --> lib/src/rdb/datastore.rs:108:70
    |
108 |     fn vertex_query_to_iterator(&self, q: VertexQuery) -> Result<Box<dyn Iterator<Item = Result<VertexItem>>>> {
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
   --> lib/src/rdb/datastore.rs:159:66
    |
159 |     fn edge_query_to_iterator(&self, q: EdgeQuery) -> Result<Box<dyn Iterator<Item = Result<EdgeRangeItem>>>> {
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
   --> lib/src/rdb/managers.rs:316:21
    |
316 |     ) -> Result<Box<dyn Iterator<Item = Result<EdgeRangeItem>>>> {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
   --> lib/src/rdb/managers.rs:458:21
    |
458 |     ) -> Result<Box<dyn Iterator<Item = Result<EdgeMetadataItem>> + 'a>> {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `indradb-lib`.
```
I'm working on MacOS, so not sure if this is problem of OS, or if this is known project.
Do you know something about it?

Thanks.

**Comment by mawhidby** [comment]
@djKooks I was able to build the latest and greatest on MacOS (I'm just on Sierra 10.12.6) -- could you post some of your environment details as well? Rust version, etc. Thanks!

**Comment by ysimonson** [comment]
This would come up if you're using an old version of rust stable

**Comment by djKooks** [comment]
@mawhidby @ysimonson thanks for reply! My rustc version is 1.26.0.
Is it unsupported?

**Comment by ysimonson** [comment]
Yes - you need 1.27 or higher

**Comment by djKooks** [comment]
@ysimonson thanks, it seems working!
Also, is it `cargo build` instead of `cargo install`? Because 'install' is not working, but 'build' works.

Please check. Thanks.

**Comment by ysimonson** [comment]
Install will build optimized targets and put them in the proper place. If it's failing, it's probably because binaries already exist and need to be replaced, in which case you do cargo install --force or cargo install --replace (can't remember off the top of my head.) If that doesn't work, you can do cargo build --release and manually copy the binaries to their proper place. Or just use the GitHub releases.

**Comment by djKooks** [comment]
@ysimonson oh, I mean it is about guide in README.
It has written as...
```
...
Clone the repo: git clone git@github.com:indradb/indradb.git.
Build/install it: cargo install.
...
```
Is it correct?

**Comment by ysimonson** [comment]
Right, that should work for most environments, unless an older version of IndraDB has already been installed

**Comment by djKooks** [comment]
@mawhidby thanks! I'll check again.
