### ISSUE TITLE
Question on start-on

### ISSUE THREAD

**Issue by djKooks** [indradb/indradb#34]
Hello
While starting on the project, I have several questions.
After I started server,
```
/bin $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `/Users/kwangin/workspace/indradb/target/debug/indradb`
Listening on 0.0.0.0:8000
```
I called `http://0.0.0.0:8000/get_global_metadata` in browser, and it returns
```
{"error":"No route found"}
```

It works same after I work with downloaded package. Is it correct result if there is no data?
Also, is there other way to store data without using lua script? I couldn't find guide about it.

Thanks.

**Comment by mawhidby** [comment]
Hey @djKooks, you can also use the transaction HTTP API to manipulate data without using the Lua scripts: https://indradb.github.io/http-api.html (See the `POST /transaction` section)

**Comment by mawhidby** [comment]
Additionally, you should be able to get the `get_global_metadata` call working if you use it as part of a POST to the transaction API. For example:

```curl -X POST -d [{ "action": "get_global_metadata" }] localhost:8000/transaction```

**Comment by djKooks** [comment]
@mawhidby thanks for help.

When I try ``:
```
curl -X POST -d [{ "action": "get_global_metadata" }] localhost:8000/transaction
```

So I tried as `curl -X POST -H "Content-Type: application/json" -d '[{ "action": "get_global_metadata" }]' http://0.0.0.0:8000/transaction`:
```
{"error":"Item #0: Unknown action"}
```
It seems this error came from indradb, right?
Could you check what am I doing wrong?

Thanks.

**Comment by mawhidby** [comment]
@djKooks You're right, totally forgot that the global_metadata endpoints were removed as of v0.13, we need to update that documentation on the HTTP API -- I opened https://github.com/indradb/indradb.github.io/issues/1 for that.

Here's some commands you could use to get started:

```
# Create 2 vertices of type "people"
curl -X POST -H "Content-Type: application/json" -d '[{"action": "create_vertex_from_type", "type": "person" }, { "action": "create_vertex_from_type", "type": "person"}]' http://localhost:8000/transaction

# Define an edge between the two vertices that were returned in the previous command
curl -X POST -H "Content-Type: application/json" -d '[{"action": "create_edge", "key": { "inbound_id": "<vertex-1-from-prev-command>", "type": "likes", "outbound_id": "<vertex-2-from-prev-command>"}  }]' http://localhost:8000/transaction

# Query for all vertices, and the edge we created:
curl -X POST -H "Content-Type: application/json" -d '[{ "action": "get_vertices", "query": { "type": "all", "start_id": null, "limit": 1000 }}, { "action": "get_edges", "query": { "type": "edges", "keys": [{ "inbound_id": "18449f46-8ee5-11e8-8000-000000000000", "type": "likes", "outbound_id": "26982a72-8ee5-11e8-8001-000000000000"}]}}]' localhost:8000/transaction
```

**Comment by djKooks** [comment]
@mawhidby it's working now, thanks!
