### ISSUE TITLE
Extracting Multiple Properties With One Query

### ISSUE THREAD

**Issue by turnersr** [indradb/indradb#58]
Hi,

Great library! 

I am trying to use it, and I had a question about returning multiple properties. 

Is it possible to extract multiple node properties in one query? My current approach requires me to create multiple queries for each property. I currently use ids returned from a `RangeVertexQuery` to create a `SpecificVertexQuery` and finally merge results using a hashmap. 

Is there a better way?

**Comment by ysimonson** [comment]
Thanks!

You have to create a query for each property you want, but not for each vertex. You can pass in your range vertex query directly into `getVertexProperties`.

**Comment by turnersr** [comment]
Cool, I think that is what I am doing, but I still have to manually merge. 
```    
let f = trans.get_vertex_properties(query_1.clone()).unwrap();
....
    let mut id_list = Vec::new();
    for vertex in f.iter() {
        id_list.push(vertex.id);
        println!("{:x?}", vertex.id);
    }

 let q =  SpecificVertexQuery::new(id_list).property("NAME");
 let mut range = trans.get_vertex_properties(q.clone()).unwrap();
```

At this point, I have `f` and `range` which are vectors of VertexProperty. They are share in common the node id, but I have to manually merge them if I want a vector of `(id, property_from_f, property_from_range)`.

**Comment by ysimonson** [comment]
It would be something like this:

```rust
// create the query of the vertices you want to select
let q = VertexQuery::Range(...);

// get the name property for the vertices that would be selected with q
let names = trans.get_vertex_properties(q.clone().property("name")).unwrap();

// get the age property for the same vertices
let ages = trans.get_vertex_properties(q.clone().property("age")).unwrap();
```

**Comment by turnersr** [comment]
Nice! Then is this the best way to merge the information? 

```
fn merge_queries(merged: &mut HashMap<uuid::Uuid, Vec<String>>, results: std::vec::Vec<std::vec::Vec<VertexProperty>>)
 {
    for vector in results.iter() {
        for vertex in vector {
            let current = merged.entry(vertex.id).or_insert(Vec::new());
            current.push(vertex.value.to_string());
        }
    }
}
    
let mut names_ages: HashMap<uuid::Uuid, Vec<String>> = HashMap::new();

merge_queries(&mut names_ages, [names, ages].to_vec());
```

**Comment by ysimonson** [comment]
Yeah, that would be one way to do it

**Comment by turnersr** [comment]
Cool beans! Thanks for your help.
