### ISSUE TITLE
Knowing which Vertex had a Property

### ISSUE THREAD

**Issue by turnersr** [indradb/indradb#61]
When using `get_vertex_properties` it would be nice to know which vertex had the property and which ones did not. When using `get_vertex_properties` with a `SpecificVertexQuery::new` query, if a node does not have the property there is no way to tell. If a query had 10 node ids and only one of them had the property then an only one result is returned and it's not clear what node that result belongs to.  

Is there a way around this without looping over each node and using `SpecificVertexQuery::single` queries? 

thanks!

**Comment by ysimonson** [comment]
The returned `VertexProperty` struct includes the vertex ID

**Comment by turnersr** [comment]
Isn't that ID the id of the returned vertex with the property? How do I know which of the initial nodes in the query resulted in the returned vertex with the property?

**Comment by ysimonson** [comment]
You'd compare the IDs of the returned VertexProperties with the IDs of the input SpecificVertexQuery

**Comment by turnersr** [comment]
Thanks for your help. I think I am missing something. 

Here is what the query looks like 

```Rust
    let query_2 = SpecificVertexQuery::new(id_list)
        .inbound(u32::MAX)
        .t(Type::new("A").unwrap())
        .outbound(u32::MAX)
        .t(Type::new("N").unwrap())
        .inbound(u32::MAX)
        .t(Type::new("A").unwrap())
        .outbound(u32::MAX)
        .t(Type::new("F").unwrap())
        .property("NAME");
```

The result is one VertexProperty: 

```
 VertexProperty {
            id: 00000000-0000-0000-0000-000000000001,
            value: String(
                "TESTNAME"
            )
        }
````

In this case, that returned ID is not any of the IDs in the initial query. The ID returned is from the vertex found with the query, but I can't map that back to any of the initial input IDs to SpecificVertexQuery.

**Comment by ysimonson** [comment]
Ah I see. You're making multiple hops away from the vertices in `id_list`, so there may have been multiple paths to get to the output vertex IDs. If you need to find how they're associated, you would indeed need to make a query for each vertex ID.

**Comment by turnersr** [comment]
:(. Dang. It's really slow when I loop and much faster as a batch query.

Maybe I can add a other type of query that supports telling which vertex the results came from?

**Comment by ysimonson** [comment]
I've been thinking about this, but it's unclear to me still how to do that in a manner that would be ergonomic and efficient. Was there a specific idea you had in mind?
