### ISSUE TITLE
Run server from source

### ISSUE THREAD

**Issue by djKooks** [indradb/indradb#62]
Hello
How can I run the db server from source? Seems `cargo run` is not exist in current configurations...

I couldn't find more detail in README.

Thanks.

**Comment by ysimonson** [comment]
`cargo run` should work, did you get an error?

**Comment by djKooks** [comment]
@ysimonson oh, sorry. Now it works well...seems something was wrong in my computer. Thanks.

One more, I'm trying to test the database with http APIs, but couldn't find document. Seems https://indradb.github.io/ is the homepage, but cannot find the link to API document(I remember I saw it before).
Could you check it?

**Comment by ysimonson** [comment]
There was some churn with the API interface a while ago, and I got rid of the HTTP API in favor of Cap'n Proto.

What language are you going to use? That can help me guide you better.

**Comment by djKooks** [comment]
@ysimonson oh, I'm trying to access with javascript. Could you give me some guide?

**Comment by ysimonson** [comment]
Here's the capnproto node.js library: https://github.com/capnproto/node-capnp

Follow its setup instructions, and use this schema: https://github.com/indradb/indradb/blob/master/bin/indradb.capnp

**Comment by ysimonson** [comment]
Going to close this out, feel free to open a new ticket if you get stuck on using another language.
