### ISSUE TITLE
Method to select vertex with specific property value

### ISSUE THREAD

**Issue by favilo** [indradb/indradb#69]
I've been going over the code, and I'm not sure if there is currently a method to select a Vertex that has a specific property.

For instance, if I have a collection of vertices with a `name` property, how would I select all the vertices with the `name` property and a value of `'Joyce'`.

**Comment by ysimonson** [comment]
That's correct. There's no built-in way to do that because the current underlying implementations do not index property values. If properties values were indexed, it would be possible to do this efficiently, but it would slow down updates and writes.

**Comment by favilo** [comment]
Alright, I've been thinking about writing support for this. But I think I want to wait for transactions to drop in [the RocksDB crate][1]. But I may fork locally and see if there is anything I can do, in the short term. You may see a pr from me in the coming weeks as I work on this in my off-time


[1]: https://github.com/rust-rocksdb/rust-rocksdb/pull/250/files

**Comment by ysimonson** [comment]
Sounds good! I'll be offline & unresponsive for the next couple of weeks, but will be around to review and answer questions after that.
