### ISSUE TITLE
support queries without limit

### ISSUE THREAD

**Issue by lammermann** [indradb/indradb#70]
Hi,
I'd often like to query all available vertices/edges in a query rather than limiting it to a number i don't  know beforehand.

```rust
let query = SpecificVertexQuery::single(uuid::default()).outbound().t("Test").outbound().t("MyVertex");
```
This is my default use case.

Mostly I limit only the final result (no matter how deeply chained the query is).

```rust
let vertices = transaction.get_vertices(query.limit(50));
```

Is it possible to support that api?

Thanks for that great library.

**Comment by ysimonson** [comment]
That does look nicer, and I'd happy merge in a PR that makes that change to the API. In the mean-time, you can pass in [`u32::max_value()`](https://doc.rust-lang.org/std/primitive.u32.html#method.max_value) for the limit, which is almost certainly more than there's memory for.
