### ISSUE TITLE
Performance Issue when dropping Vec that is returned by get_all_vertex_properties()

### ISSUE THREAD

**Issue by ra-martin** [indradb/indradb#74]
Heyhu,

in my project I need to select all vertices (and all of their respective properties) that match a given type:

```rust
let tag = String::from("TestTag");
let transaction = self.datastore.transaction().unwrap();
let type_filter = Type::new(tag).unwrap();
let vq = RangeVertexQuery::new(u32::MAX).t(type_filter);
let start_timestamp = Instant::now();
let vertices = transaction.get_all_vertex_properties(vq).unwrap();

println!("After get_all_vertex_properties: {:?}", start_timestamp.elapsed());
println!("Vertices; Len: {:?}", vertices.len());

drop(vertices);
println!("After drop of vertices: {:?}", start_timestamp.elapsed());
```
Fetching the vertices is moderately fast, however, I was confused about how long it took to return from the function. It turned out that dropping the "vertices"-Vec takes quite some time (with --release):

```
After get_all_vertex_properties: 284.387385ms
After drop of vertices: 490.460397ms
Dropping took: 206.073012ms
```

Flame-Graph corresponding with the drop:

<img width="1202" alt="Screenshot 2019-12-31 at 16 15 55" src="https://user-images.githubusercontent.com/15673326/71625573-da1d9400-2be8-11ea-80d9-ce3711f64e2a.png">

I only recently started using Rust, so I'm not sure how to investigate the issue. I created a repository that contains a project that replicates this behaviour:

https://github.com/ra-martin/IndraDropIssue

Thanks for maintaining such a cool project!

**Comment by ysimonson** [comment]
Thanks for the thorough investigation! Because vertices is just a `Vec` of simple structs, I believe this is just the time taken to free up memory.

**Comment by ra-martin** [comment]
Hmmm... I thought Vec's were allocated as a single segment in memory? I tried populating a Vec with millions of simple structs but dropping it never took more than a few ms in my tests.
Also, I'm confused by the BTreeMap drop() that happens as a result of dropping "vertices" in the example above. How is such a Map even involved in dropping a Vec of structs that have nothing to do with the Map?

I'll investigate further in 2020 ;)

**Comment by ysimonson** [comment]
Hm yeah, that is strange - `get_all_vertex_properties` copies all values into a `Vec`, so there should be no `BTreeMap` involved. Is the underlying data deleted from the datastore? If so, that would imply a serious bug.

**Comment by ra-martin** [comment]
i introduced a new function:

```rust
#[inline(never)]
fn proxy(v: Vec<VertexProperty>) {
    println!("...in proxy");
    drop(v);
    println!("dropped.");
}
```

Call:

```rust
        let vertices = transaction.get_vertex_properties(vq).unwrap();
        println!("After get_all_vertex_properties: {:?}", start_timestamp.elapsed());
        proxy(vertices);
        println!("After drop of vertices {:?}", start_timestamp.elapsed());
```

<img width="1204" alt="Screenshot 2020-01-01 at 23 59 10" src="https://user-images.githubusercontent.com/15673326/71647158-bd6d8300-2cf2-11ea-8633-174e8909934e.png">

You can clearly see the BTreeMap-drops in the Flamegraph. Im running

`stable-x86_64-apple-darwin unchanged - rustc 1.40.0 (73528e339 2019-12-16)`

by the way.

Running the `get_vertex_properties()`repeatedly returns the same Vec, apparently the data is not dropped from the datastore itself. Very weird indeed.

**Comment by ysimonson** [comment]
That's good that it's not deleting the underlying data. It makes me wonder if there's actually an issue with the flame graph itself, or maybe we're misinterpreting it.

**Comment by ysimonson** [comment]
I'm convinced that this is the cost of dropping. Consider that:

- It's dropping 100,000 `VertexProperty` instances, each of which has a JSON map with 20 entries in it.
- Between the vec and the JSON maps, a bunch of heap traversals need to be done.
- Freeing memory can be costly if the memory has to be returned to the kernel.

Here's a simplified example (built off your repo, thank you for that!) that doesn't use a datastore, but creates a `Vec` of the same size. It takes the same amount of time to drop.

```rust
#[macro_use]
extern crate serde_json;
extern crate indradb;

use std::time::Instant;
use uuid::Uuid;
use std::collections::HashMap;
use serde_json::Value;

pub fn get_all_with_tag() {
    let prop_idents: Vec<String> = (0..20).map(|_| {
        Uuid::new_v4().to_string()
    }).collect();

    let mut k: HashMap<String, Value> = HashMap::new();
    for (i, p) in prop_idents.clone().into_iter().enumerate() {
        k.insert(p, json!(i));
    }
    let value = serde_json::to_value(&k).unwrap();

    let ts = Instant::now();
    let mut vertices = Vec::new();
    for _ in 0..100_000 {
        vertices.push(indradb::VertexProperty {
            id: Uuid::new_v4(),
            value: value.clone(),
        });
    }
    println!("insert: {:?}", ts.elapsed());
    
    let ts = Instant::now();
    drop(vertices);
    println!("drop: {:?}", ts.elapsed());
}

fn main() {
    get_all_with_tag();
}
```

```
insert: 310.366715ms
drop: 320.155586ms
```

**Comment by ysimonson** [comment]
I'm going to consider this resolved, but let me know if anything else turns up
