### ISSUE TITLE
Sled backend?

### ISSUE THREAD

**Issue by thedodd** [indradb/indradb#79]
Hello! Excellent work on this project so far. I'm stoked to try it out. Any plans to implement a Sled backend for this project per chance?

Either way, it looks like the interface is pretty straightforward, and Sled does offer a transactional interface. Thoughts on implementation?

**Comment by ysimonson** [comment]
Thanks! [I tried sled earlier](https://github.com/indradb/indradb/releases/tag/archive%2Fsled-datastore), but performance was quite poor relative to rocksdb. It is possible it's improved since, and it would be fairly straight-forward to take the work in there and modernize it for a newer version of IndraDB, if you or anyone else wants to give it a whirl.

**Comment by jespersm** [comment]
I did it for sled back when it was version 0.24, easy enough. Performance was not as good as RocksDB, but it might be affected by the need for 

Back then, it didn't have transactions across trees, you should add that.

My branch: https://github.com/jespersm/indradb/tree/sled

**Comment by jespersm** [comment]
I just ran it here:

RocksDB:
```
% cargo +nightly bench --features=bench-suite,rocksdb-datastore
...
test rdb::bulk_load_optimized_config::bench_create_edge    ... bench:       8,779 ns/iter (+/- 1,905)
test rdb::bulk_load_optimized_config::bench_create_vertex  ... bench:       4,491 ns/iter (+/- 768)
test rdb::bulk_load_optimized_config::bench_get_edge_count ... bench:       1,934 ns/iter (+/- 104)
test rdb::bulk_load_optimized_config::bench_get_edges      ... bench:       1,127 ns/iter (+/- 83)
test rdb::bulk_load_optimized_config::bench_get_vertices   ... bench:         961 ns/iter (+/- 73)
test rdb::normal_config::bench_create_edge                 ... bench:       9,599 ns/iter (+/- 2,129)
test rdb::normal_config::bench_create_vertex               ... bench:       4,525 ns/iter (+/- 1,607)
test rdb::normal_config::bench_get_edge_count              ... bench:       1,936 ns/iter (+/- 136)
test rdb::normal_config::bench_get_edges                   ... bench:       1,127 ns/iter (+/- 76)
test rdb::normal_config::bench_get_vertices                ... bench:         972 ns/iter (+/- 88)
```

Sled:
```
% cargo +nightly bench --features=bench-suite,sled-datastore
...
test sledds::bench_create_edge    ... bench:      30,657 ns/iter (+/- 3,368)
test sledds::bench_create_vertex  ... bench:       8,880 ns/iter (+/- 1,895)
test sledds::bench_get_edge_count ... bench:       2,536 ns/iter (+/- 320)
test sledds::bench_get_edges      ... bench:       1,828 ns/iter (+/- 257)
test sledds::bench_get_vertices   ... bench:       1,710 ns/iter (+/- 214)

test result: ok. 0 passed; 0 failed; 10 ignored; 10 measured; 0 filtered out
```
But the notes above apply, I'm no Rust or Sled expert.

**Comment by ysimonson** [comment]
Those results are a lot closer than what I recall! It looks like reads have gotten much better but writes are still lagging. This seems to align with what people have said about Sled; it offers less operational complexity and good read performance, but at the expense of write performance vs rocksdb.

IndraDB's write performance is already not great though as-is; [importing the wikipedia dataset](https://github.com/indradb/wikipedia-example) is a slog.

**Comment by jespersm** [comment]
I took the time to update my sled branch to both the latest and greatest IndraDB, but also the newest Sled version. And that was pleasant, again with RocksDB as the basis:

```
test rdb::normal_config::bench_bulk_insert                 ... bench: 101,019,594 ns/iter (+/- 3,161,975)
test rdb::normal_config::bench_create_edge                 ... bench:       8,890 ns/iter (+/- 2,127)
test rdb::normal_config::bench_create_vertex               ... bench:       4,515 ns/iter (+/- 1,280)
test rdb::normal_config::bench_get_edge_count              ... bench:       1,910 ns/iter (+/- 243)
test rdb::normal_config::bench_get_edges                   ... bench:       1,291 ns/iter (+/- 148)
test rdb::normal_config::bench_get_vertices                ... bench:       1,170 ns/iter (+/- 106)
```

But now with Sled 0.31.0:

```
test sledds::bench_bulk_insert    ... bench: 257,300,015 ns/iter (+/- 10,269,653)
test sledds::bench_create_edge    ... bench:       8,109 ns/iter (+/- 482)
test sledds::bench_create_vertex  ... bench:       4,461 ns/iter (+/- 354)
test sledds::bench_get_edge_count ... bench:       1,543 ns/iter (+/- 178)
test sledds::bench_get_edges      ... bench:       1,096 ns/iter (+/- 52)
test sledds::bench_get_vertices   ... bench:         962 ns/iter (+/- 63)
```

Faster for all workloads except bulk inserts!

Great work on Sled by Tyler / Spacejam! PR forthcoming, if you're interested. I'm sure there are several places where the performance could be improved further, by the way, since I'm a Rust n00b, after all.

**Comment by thedodd** [comment]
Wow, that's awesome! Thanks for revitalizing the effort with the Sled backend. I'll do my best to give that PR an eye here soon.

**Comment by luke-biel** [comment]
Hey, just wanted to check out what's the status of the PR. Is there a chance this would be merged soon?

**Comment by ysimonson** [comment]
Added in https://github.com/indradb/indradb/pull/89, will go out with 1.1.0 shortly.
