### ISSUE TITLE
Can you add some benchmarks for read writes and complex queires

### ISSUE THREAD

**Issue by dgandhi17** [indradb/indradb#93]
I am planning to use this embedded library in my app but before that I want to see some benchmark. Can you add ?
it will help

**Comment by ysimonson** [comment]
There's already built-in benchmarks, run `make bench` to see the results.

**Comment by dgandhi17** [comment]
Seems doesnt work, it will be better if you can publish some graph for the result

**Comment by ysimonson** [comment]
I'd need more details to figure out what's wrong with the benchmark runner. Most likely rust nightly isn't installed.

**Comment by ysimonson** [comment]
Going to close this out, but let me know if you have more details to share
