### ISSUE TITLE
How migration works with this DB

### ISSUE THREAD

**Issue by dgandhi17** [indradb/indradb#95]

**Comment by ysimonson** [comment]
A guide would be useful: https://github.com/indradb/indradb.github.io/issues/3

Generally, the idea is to use bulk insert. See this example, which reads a large compressed XML file, and crates a bunch of bulk insert requests from it: https://github.com/indradb/wikipedia-example/blob/master/crawler.py

**Comment by dgandhi17** [comment]
I mean to say schema migration. Node, edges, properties

**Comment by ysimonson** [comment]
IndraDB doesn't have a schema, in the sense that you don't need to decide the structure of nodes, properties and edges ahead-of-time.

**Comment by ysimonson** [comment]
I think everything's answered here
